eureka:
  instance:
    hostname: localhost
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka

server:
  port: 8091

spring:
  application:
    name: products
  config:
    import: optional:configserver:http://localhost:8888
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/microservices
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
